<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test1"
           tests="3"
           failures="1"
           errors="0"
           skipped="2"
           time="42.572">
  <properties />
            <testcase name="loginTest01" time="11.747" classname="com.first.testcases.LoginTest">
                <failure type="java.lang.AssertionError"
                  message="查找元素异常，退出当前测试用例"
              >
<![CDATA[java.lang.AssertionError: 查找元素异常，退出当前测试用例
  org.testng.Assert.fail(Assert.java:94)
  com.first.uiframework.WebElementUtils.getElement(WebElementUtils.java:54)
  com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:63)
  com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:1)
  org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
  com.first.uiframework.WebElementUtils.findElement(WebElementUtils.java:61)
  com.first.uiframework.WebElementUtils.input(WebElementUtils.java:76)
  com.first.pages.LoginPage.inputUserName(LoginPage.java:30)
  com.first.actions.LoginOperate.LoginSuess(LoginOperate.java:25)
  com.first.actions.LoginOperate.getLoginName(LoginOperate.java:32)
  com.first.testcases.LoginTest.loginTest01(LoginTest.java:45)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.retryFailed(Invoker.java:967)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
      </failure>

          </testcase>
  
            <testcase name="loginTest01" time="0.0" classname="com.first.testcases.LoginTest">
          <skipped />
    </testcase>
            <testcase name="loginTest01" time="0.0" classname="com.first.testcases.LoginTest">
          <skipped />
    </testcase>
  
  
</testsuite>
