<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="李琦" name="com.first.testcases.LoginTest" tests="3" failures="3" timestamp="26 Mar 2017 10:47:12 GMT" time="142.889" errors="0">
  <testcase name="loginTest01" time="31.381" classname="com.first.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="查找元素异常，退出当前测试用例">
      <![CDATA[java.lang.AssertionError: 查找元素异常，退出当前测试用例
	at org.testng.Assert.fail(Assert.java:94)
	at com.first.uiframework.WebElementUtils.getElement(WebElementUtils.java:54)
	at com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:63)
	at com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.first.uiframework.WebElementUtils.findElement(WebElementUtils.java:61)
	at com.first.uiframework.WebElementUtils.input(WebElementUtils.java:76)
	at com.first.pages.LoginPage.inputUserName(LoginPage.java:30)
	at com.first.actions.LoginOperate.LoginSuess(LoginOperate.java:25)
	at com.first.actions.LoginOperate.getLoginName(LoginOperate.java:32)
	at com.first.testcases.LoginTest.loginTest01(LoginTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- loginTest01 -->
  <testcase name="loginTest01" time="31.330" classname="com.first.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="查找元素异常，退出当前测试用例">
      <![CDATA[java.lang.AssertionError: 查找元素异常，退出当前测试用例
	at org.testng.Assert.fail(Assert.java:94)
	at com.first.uiframework.WebElementUtils.getElement(WebElementUtils.java:54)
	at com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:63)
	at com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.first.uiframework.WebElementUtils.findElement(WebElementUtils.java:61)
	at com.first.uiframework.WebElementUtils.input(WebElementUtils.java:76)
	at com.first.pages.LoginPage.inputUserName(LoginPage.java:30)
	at com.first.actions.LoginOperate.LoginSuess(LoginOperate.java:25)
	at com.first.actions.LoginOperate.getLoginName(LoginOperate.java:32)
	at com.first.testcases.LoginTest.loginTest01(LoginTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- loginTest01 -->
  <testcase name="loginTest01" time="80.178" classname="com.first.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="查找元素异常，退出当前测试用例">
      <![CDATA[java.lang.AssertionError: 查找元素异常，退出当前测试用例
	at org.testng.Assert.fail(Assert.java:94)
	at com.first.uiframework.WebElementUtils.getElement(WebElementUtils.java:54)
	at com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:63)
	at com.first.uiframework.WebElementUtils$1.apply(WebElementUtils.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.first.uiframework.WebElementUtils.findElement(WebElementUtils.java:61)
	at com.first.uiframework.WebElementUtils.input(WebElementUtils.java:76)
	at com.first.pages.LoginPage.inputUserName(LoginPage.java:30)
	at com.first.actions.LoginOperate.LoginSuess(LoginOperate.java:25)
	at com.first.actions.LoginOperate.getLoginName(LoginOperate.java:32)
	at com.first.testcases.LoginTest.loginTest01(LoginTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- loginTest01 -->
</testsuite> <!-- com.first.testcases.LoginTest -->
